<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="pkuma-5520" name="com.tests.TestGet" tests="5" failures="0" timestamp="08 Nov 2018 10:23:52 GMT" time="4.666" errors="1">
  <testcase name="testGetServices" time="0.539" classname="com.tests.TestGet">
    <error type="com.n26.exceptions.WebServicesException" message="java.lang.Throwable: Failed to validate status code of the response">
      <![CDATA[com.n26.exceptions.WebServicesException: java.lang.Throwable: Failed to validate status code of the responseat com.n26.utilities.CustomKeywords.validateStatusCode(CustomKeywords.java:167)at com.tests.TestGet.testGetServices(TestGet.java:35)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)Caused by: java.lang.Throwable: Failed to validate status code of the response... 27 more]]>
    </error>
  </testcase> <!-- testGetServices -->
  <testcase name="testGetServices" time="0.540" classname="com.tests.TestGet"/>
  <testcase name="testGetServices" time="2.185" classname="com.tests.TestGet"/>
  <testcase name="testGetServices" time="0.772" classname="com.tests.TestGet"/>
  <testcase name="testGetServices" time="0.630" classname="com.tests.TestGet"/>
</testsuite> <!-- com.tests.TestGet -->
